# ----- Redis
redisson-config: redisson-test.yaml

# ----- distributed-task-module
distributed-task-module:
  enabled: true

# ----- nacos
namingClientBeatThreadCount: 2
namingPollingThreadCount: 2

# ----- quartz
org.quartz.threadPool:
  threadCount: 2
