package com.curtisnewbie.service.auth.infrastructure.repository.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.curtisnewbie.service.auth.dao.AccessLog;
import org.apache.ibatis.annotations.Param;

import java.time.LocalDateTime;
import java.util.List;

public interface AccessLogMapper extends BaseMapper<AccessLog> {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    AccessLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    List<AccessLog> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table access_log
     *
     * @mbg.generated Sun May 23 23:31:27 CST 2021
     */
    int updateByPrimaryKey(AccessLog record);

    List<AccessLog> selectAllBasicInfo();

    List<Integer> selectIdsBeforeDate(@Param("date") LocalDateTime date);

    void copyToHistory(@Param("ids") List<Integer> ids);

    void deleteByIds(@Param("ids") List<Integer> ids);
}