package com.curtisnewbie.service.auth.infrastructure.repository.mapper;

import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.curtisnewbie.common.util.EnhancedMapper;
import com.curtisnewbie.service.auth.dao.App;

import java.util.List;

/**
 * <p>
 * Mapper for application
 * </p>
 * @author yongjie.zhuang
 */
public interface AppMapper extends EnhancedMapper<App> {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    IPage<App> selectAll(Page p);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    int updateByPrimaryKey(App record);

    /**
     * select id, name
     */
    List<App> selectAllBriefInfo();
}