package com.curtisnewbie.service.auth.infrastructure.repository.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.curtisnewbie.service.auth.dao.EventHandling;
import org.apache.ibatis.annotations.Param;

import java.time.LocalDateTime;
import java.util.List;

public interface EventHandlingMapper extends BaseMapper<EventHandling> {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table event_handling
     *
     * @mbg.generated Sun Aug 29 23:47:48 CST 2021
     */
    EventHandling selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table event_handling
     *
     * @mbg.generated Sun Aug 29 23:47:48 CST 2021
     */
    List<EventHandling> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table event_handling
     *
     * @mbg.generated Sun Aug 29 23:47:48 CST 2021
     */
    int updateByPrimaryKey(EventHandling record);

    /**
     * Select * by status, type
     */
    IPage<EventHandling> selectByPage(Page p, @Param("p") EventHandling eventHandling);

    int updateHandlingResult(@Param("id") int id, @Param("prevStatus") int prevStatus, @Param("currStatus") int currStatus
            , @Param("handlerId") int handlerId, @Param("handleTime") LocalDateTime handleTime, @Param("handleResult") int handleResult);

    Integer selectTypeById(int id);
}