package com.curtisnewbie.service.auth.infrastructure.repository.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.curtisnewbie.service.auth.dao.App;
import com.curtisnewbie.service.auth.dao.UserApp;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * <p>
 * Mapper for user_app
 * </p>
 *
 * @author yongjie.zhuang
 */
public interface UserAppMapper extends BaseMapper<UserApp> {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_app
     *
     * @mbg.generated Mon Sep 06 20:39:30 CST 2021
     */
    int insert(UserApp record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_app
     *
     * @mbg.generated Mon Sep 06 20:39:30 CST 2021
     */
    List<UserApp> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_app
     *
     * @mbg.generated Mon Sep 06 20:39:30 CST 2021
     */
    int updateByPrimaryKey(UserApp record);

    /**
     * select 1
     */
    Integer selectOneIfUserIsAllowed(@Param("userId") int userId, @Param("appName") String appName);

    /**
     * select app.id, app.name
     */
    List<App> getAppsPermittedForUser(@Param("userId") int userId);

    /**
     * delete all apps for user
     */
    void clearAppsForUser(@Param("userId") int userId);

    /**
     * insert by user_id and one or more app_id
     */
    void setAppsForUser(@Param("userId") int userId, @Param("appIdList") List<Integer> appIdList);
}