version: "3.9"
services:

  auth-service:
    image: curtisnewbie/auth-service 
    ports:   
      - "8080:8081"
      - "9090:9091"
    networks:
      - backend

  redis-server:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend 

  rabbitmq-server:
    image: rabbitmq:3.9.7-management-alpine 
    ports: 
      - "5672"
    networks:
      - backend

  nacos-server:
    image: nacos/nacos-server 
    environment:
      - MODE=standalone
    ports:
      - "8848"
    networks:
      - backend

networks:
  backend:
  
    
