package com.curtisnewbie.service.auth.dao;

import com.curtisnewbie.service.auth.dao.App;

import java.util.List;

/**
 * <p>
 * Mapper for application
 * </p>
 * @author yongjie.zhuang
 */
public interface AppMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    int insert(App record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    App selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    List<App> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table app
     *
     * @mbg.generated Mon Sep 06 20:38:55 CST 2021
     */
    int updateByPrimaryKey(App record);
}