package com.curtisnewbie.service.auth.dao;

import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * <p>
 * Mapper for user_app
 * </p>
 *
 * @author yongjie.zhuang
 */
public interface UserAppMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_app
     *
     * @mbg.generated Mon Sep 06 20:39:30 CST 2021
     */
    int insert(UserApp record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_app
     *
     * @mbg.generated Mon Sep 06 20:39:30 CST 2021
     */
    List<UserApp> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table user_app
     *
     * @mbg.generated Mon Sep 06 20:39:30 CST 2021
     */
    int updateByPrimaryKey(UserApp record);

    /**
     * select 1
     */
    Integer selectOneIfUserIsAllowed(@Param("userId") int userId, @Param("appName") String appName);
}